# Generated by Django 2.2.27 on 2022-02-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InboxModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=17)),
                ('subject', models.CharField(blank=True, max_length=250, null=True)),
                ('message', models.TextField(blank=True, max_length=5000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Inbox',
                'verbose_name_plural': 'Inbox',
                'ordering': ('-created_at',),
            },
        ),
    ]
