# Generated by Django 2.2.27 on 2022-02-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallerymodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymodel',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
