# Generated by Django 2.2.27 on 2022-02-26 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0024_auto_20220214_1209'),
        ('gallery', '0004_auto_20220226_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerymodel',
            name='image',
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='home_preview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gallery_home_preview', to='home_two.PhotoModel'),
        ),
    ]
