# Generated by Django 2.2.27 on 2022-02-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_gallerymodel_gallery_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymodel',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
