# Generated by Django 2.2.27 on 2022-02-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_gallerymodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymodel',
            name='occured_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
