# Generated by Django 2.2.27 on 2022-02-26 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0024_auto_20220214_1209'),
        ('gallery', '0008_gallerymodel_occured_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymodel',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='keywords',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='layout_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gallery_layout_image', to='home_two.PhotoModel'),
        ),
    ]
