# Generated by Django 2.2.27 on 2022-02-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_auto_20220227_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerydetailsectionmodel',
            options={'verbose_name': 'Gallery detail section', 'verbose_name_plural': 'Gallery detail section'},
        ),
    ]
