# Generated by Django 2.2.27 on 2022-02-14 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apaboutsectionmodel',
            old_name='subheading',
            new_name='sub_heading',
        ),
    ]
