# Generated by Django 2.2.27 on 2022-02-14 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_auto_20220214_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apaboutsectionmodel',
            old_name='sub_heading',
            new_name='subheading',
        ),
    ]
