# Generated by Django 2.2.27 on 2022-02-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0008_faqmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqmodel',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
    ]
