# Generated by Django 2.2.27 on 2022-02-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0013_pricingareasectionmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricingAreaSectionModel',
        ),
    ]
