# Generated by Django 2.2.27 on 2022-02-20 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0024_auto_20220214_1209'),
        ('about_us', '0015_clientreviewmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientreviewsectionmodel',
            options={'verbose_name': 'Client review section', 'verbose_name_plural': 'Client review sections'},
        ),
        migrations.AddField(
            model_name='clientreviewsectionmodel',
            name='background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_review_section_background_image', to='home_two.PhotoModel'),
        ),
        migrations.AlterField(
            model_name='clientreviewsectionmodel',
            name='section_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_review_section_section_image', to='home_two.PhotoModel'),
        ),
    ]
