# Generated by Django 2.2.27 on 2022-02-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0016_auto_20220220_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreviewmodel',
            name='position',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
