# Generated by Django 2.2.27 on 2022-02-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0017_clientreviewmodel_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqsectionmodel',
            old_name='title',
            new_name='heading',
        ),
    ]
