# Generated by Django 2.2.27 on 2022-02-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
