# Generated by Django 2.2.27 on 2022-02-13 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home_two', '0022_auto_20220213_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBreadcrumbModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home_two.PhotoModel')),
            ],
            options={
                'verbose_name': 'Site breadcrumb',
                'verbose_name_plural': 'Site breadcrumbs',
            },
        ),
    ]
