# Generated by Django 2.2.27 on 2022-03-09 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_breadcrumb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebreadcrumbmodel',
            name='background_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home_two.PhotoModel'),
        ),
    ]
