# Generated by Django 2.2.27 on 2022-02-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_servicemodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
