# Generated by Django 2.2.27 on 2022-02-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_servicemodel_modified_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicemodel',
            old_name='photo',
            new_name='home_photo',
        ),
    ]
