# Generated by Django 2.2.27 on 2022-02-17 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_pricingareasectionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfPlanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Type of plan',
                'verbose_name_plural': 'Types of plan',
            },
        ),
        migrations.CreateModel(
            name='PlanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('title', models.CharField(max_length=90)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('type_of_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='service.TypeOfPlanModel')),
            ],
            options={
                'verbose_name': 'Service plan',
                'verbose_name_plural': 'Service plans',
            },
        ),
    ]
