# Generated by Django 2.2.27 on 2022-02-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_planmodel_typeofplanmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofplanmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='typeofplanmodel',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
