# Generated by Django 2.2.27 on 2022-02-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20220217_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='plans',
            field=models.ManyToManyField(blank=True, to='service.PlanModel'),
        ),
    ]
