# Generated by Django 2.2.27 on 2022-02-21 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_serviceseodetailsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceseodetailsmodel',
            options={'verbose_name': 'Service SEO Detail', 'verbose_name_plural': 'Service SEO Details'},
        ),
    ]
