# Generated by Django 2.2.27 on 2022-02-21 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0024_auto_20220214_1209'),
        ('service', '0012_serviceareasectionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='service_page_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_model_service_page_photo', to='home_two.PhotoModel'),
        ),
    ]
