# Generated by Django 2.2.27 on 2022-02-21 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_serviceaboutsectionmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceaboutsectionmodel',
            old_name='description',
            new_name='summary',
        ),
    ]
