# Generated by Django 2.2.27 on 2022-02-21 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0024_auto_20220214_1209'),
        ('service', '0017_servicesidebarsectionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesidebarsectionmodel',
            name='section_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_sidebar_section_section_image', to='home_two.PhotoModel'),
        ),
        migrations.AlterField(
            model_name='servicesidebarsectionmodel',
            name='background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_sidebar_section_background_image', to='home_two.PhotoModel'),
        ),
    ]
