# Generated by Django 2.2.27 on 2022-02-21 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0024_auto_20220214_1209'),
        ('service', '0018_auto_20220221_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='service_detail_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_model_service_detail_photo', to='home_two.PhotoModel'),
        ),
    ]
