# Generated by Django 2.2.27 on 2022-02-22 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0024_auto_20220214_1209'),
        ('service', '0021_auto_20220222_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofplanmodel',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home_two.PhotoModel'),
        ),
    ]
