# Generated by Django 2.2.27 on 2022-02-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_typeofplanmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='keywords',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
