# Generated by Django 2.2.27 on 2022-02-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_servicemodel_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceseodetailsmodel',
            name='keywords',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
