# Generated by Django 2.2.27 on 2022-02-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_auto_20220227_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingareasectionmodel',
            options={'verbose_name': 'Pricing area section', 'verbose_name_plural': 'Pricing area section'},
        ),
        migrations.AlterModelOptions(
            name='serviceaboutsectionmodel',
            options={'verbose_name': 'Service About section', 'verbose_name_plural': 'Service About section'},
        ),
        migrations.AlterModelOptions(
            name='serviceareasectionmodel',
            options={'verbose_name': 'Service area section', 'verbose_name_plural': 'Service area section'},
        ),
        migrations.AlterModelOptions(
            name='servicesidebarsectionmodel',
            options={'verbose_name': 'Service sidebar section', 'verbose_name_plural': 'Service sidebar section'},
        ),
    ]
