# Generated by Django 2.2.27 on 2022-03-04 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0030_productareasectionmodel'),
        ('service', '0025_auto_20220228_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='sidebar_photo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_model_sidebar_photo', to='home_two.PhotoModel'),
        ),
    ]
