# Generated by Django 2.2.27 on 2022-03-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_servicemodel_sidebar_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='keywords',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
