# Generated by Django 2.2.27 on 2022-03-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0027_auto_20220304_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicemodel',
            old_name='sidebar_photo',
            new_name='nav_sidebar_photo',
        ),
    ]
