# Generated by Django 2.2.27 on 2022-03-09 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0030_auto_20220309_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceaboutsectionmodel',
            name='section_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home_two.PhotoModel'),
        ),
        migrations.AlterField(
            model_name='serviceareasectionmodel',
            name='years_of_experience_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home_two.PhotoModel'),
        ),
    ]
