# Generated by Django 2.2.27 on 2022-03-09 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0031_auto_20220309_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesidebarsectionmodel',
            name='background_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_sidebar_section_background_image', to='home_two.PhotoModel'),
        ),
        migrations.AlterField(
            model_name='servicesidebarsectionmodel',
            name='section_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_sidebar_section_section_image', to='home_two.PhotoModel'),
        ),
    ]
