# Generated by Django 2.2.27 on 2022-03-09 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0034_auto_20220309_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='thumbnail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home_two.PhotoModel'),
        ),
    ]
