# Generated by Django 2.2.27 on 2022-02-12 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home_two', '0014_whychooseussectionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAuxDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('secure_url', models.URLField(blank=True, null=True)),
                ('mimeType', models.CharField(blank=True, max_length=128, null=True)),
                ('alt', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home_two.PhotoModel')),
            ],
            options={
                'verbose_name': 'Image Auxilliary data',
                'verbose_name_plural': 'Image auxilliary data',
            },
        ),
    ]
