# Generated by Django 2.2.27 on 2022-02-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_sharing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OgTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_option', models.CharField(choices=[('article', 'Article'), ('article:published_time', 'Article - Published Time - When the article was first published.'), ('article:modified_time', 'Article - Modified Time - When the article was last changed.'), ('article:expiration_time', 'Article - Expiration Time - When the article is out of date after.'), ('article:author', 'Article - Author - Writers of the article.'), ('article:section', 'Article - Article - Section - A high-level section name. E.g. Technology'), ('article:tag', 'Article - Tag -Tag words associated with this article.'), ('book', 'Book'), ('book:isbn', 'Book - ISBN - The ISBN'), ('book:release_date', 'Book - Release date - The date the book was released.'), ('book:tag', 'Book - Tag - Tag words associated with this book.'), ('profile', 'Profile'), ('profile:first_name', 'Profile - First Name - A name normally given to an individual by a parent or self-chosen.'), ('profile:last_name', 'Profile - Last Name - A name inherited from a family or marriage and by which the individual is commonly known.'), ('profile:username', 'Profile - Username - A short unique string to identify them.'), ('profile:gender', 'Profile - Gender - (male, female) - Their gender.'), ('website', 'Website')], max_length=30)),
                ('type_value', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Og type',
                'verbose_name_plural': 'Og types',
            },
        ),
    ]
