# Generated by Django 2.2.27 on 2022-02-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_sharing', '0003_ogtypemodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogtypemodel',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
