# Generated by Django 2.2.27 on 2022-02-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_sharing', '0004_ogtypemodel_modified_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OgTypeModel',
        ),
    ]
