# Generated by Django 2.2.27 on 2022-02-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_sharing', '0006_seosocialsharedatamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageauxdatamodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
