# Generated by Django 2.2.27 on 2022-02-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_sharing', '0008_imageauxdatamodel_modified_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeoSocialShareDataModel',
        ),
    ]
