# Generated by Django 2.2.27 on 2022-02-13 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_sharing', '0010_remove_imageauxdatamodel_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageauxdatamodel',
            name='secure_url',
        ),
    ]
