# Generated by Django 2.2.27 on 2022-02-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_sharing', '0011_remove_imageauxdatamodel_secure_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageauxdatamodel',
            name='mimeType',
        ),
    ]
