# Generated by Django 2.2.27 on 2022-02-13 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0017_auto_20220213_0940'),
        ('social_sharing', '0012_remove_imageauxdatamodel_mimetype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageAuxDataModel',
        ),
    ]
