# Generated by Django 2.2.27 on 2022-03-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediamodel',
            name='icon',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
