# Generated by Django 2.2.27 on 2022-02-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='flaticon',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
