# Generated by Django 2.2.27 on 2022-02-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productcategory_flaticon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='photo',
        ),
    ]
