# Generated by Django 2.2.27 on 2022-02-11 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_productcategory_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='ProductCategoryModel',
        ),
    ]
