# Generated by Django 2.2.27 on 2022-02-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_productmodel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_category', to='shop.ProductCategoryModel'),
        ),
    ]
