# Generated by Django 2.2.27 on 2022-02-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20220211_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ManyToManyField(blank=True, to='shop.ProductCategoryModel'),
        ),
    ]
