# Generated by Django 2.2.27 on 2022-02-12 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20220211_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='price',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.PriceModel'),
        ),
    ]
