# Generated by Django 2.2.27 on 2022-02-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_productmodel_total_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='keywords',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
