# Generated by Django 2.2.27 on 2022-02-23 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0024_auto_20220214_1209'),
        ('shop', '0015_auto_20220223_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_images',
            field=models.ManyToManyField(blank=True, related_name='product_model_product_images', to='home_two.PhotoModel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_preview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_model_product_preview', to='home_two.PhotoModel'),
        ),
    ]
