# Generated by Django 2.2.27 on 2022-03-09 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20220309_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='client_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home_two.PhotoModel'),
        ),
    ]
