# Generated by Django 2.2.27 on 2022-03-09 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20220309_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_preview',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_model_product_preview', to='home_two.PhotoModel'),
        ),
    ]
