# Generated by Django 2.2.27 on 2022-02-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_contactinfomodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfomodel',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
