# Generated by Django 2.2.27 on 2022-02-27 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0025_auto_20220227_1206'),
        ('contact_us', '0006_remove_contactinfomodel_address_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveUsAMessageSectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=70)),
                ('summary', models.TextField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home_two.PhotoModel')),
            ],
            options={
                'verbose_name': 'Leave us a message section',
                'verbose_name_plural': 'Leave us a message sections',
            },
        ),
    ]
