# Generated by Django 2.2.27 on 2022-02-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0007_leaveusamessagesectionmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaveusamessagesectionmodel',
            options={'verbose_name': 'Leave us a message section', 'verbose_name_plural': 'Leave us a message section'},
        ),
    ]
