# Generated by Django 2.2.27 on 2022-03-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0009_workwithusctasectionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveusamessagesectionmodel',
            name='our_promise',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
