# Generated by Django 2.2.27 on 2022-03-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0010_leaveusamessagesectionmodel_our_promise'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfomodel',
            name='can_appear_on_footer',
            field=models.BooleanField(default=False),
        ),
    ]
