# Generated by Django 2.2.27 on 2022-03-04 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home_two', '0030_productareasectionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_location', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('logo_side', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='header_section_logo_side', to='home_two.PhotoModel')),
                ('retina_logo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='header_section_retina_logo', to='home_two.PhotoModel')),
                ('standard_logo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='header_section_standard_logo', to='home_two.PhotoModel')),
            ],
            options={
                'verbose_name': 'Header section',
                'verbose_name_plural': 'Header section',
            },
        ),
    ]
