# Generated by Django 2.2.27 on 2022-03-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0002_headersectionmodel_primary_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headersectionmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='headersectionmodel',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='headersectionmodel',
            name='primary_email',
            field=models.EmailField(max_length=254),
        ),
    ]
