# Generated by Django 2.2.27 on 2022-03-04 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0030_productareasectionmodel'),
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersectionmodel',
            name='background_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='footer_section_background_image', to='home_two.PhotoModel'),
        ),
        migrations.AlterField(
            model_name='footersectionmodel',
            name='footer_logo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='footer_section_footer_logo', to='home_two.PhotoModel'),
        ),
    ]
