# Generated by Django 2.2.27 on 2022-03-04 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0030_productareasectionmodel'),
        ('footer', '0002_auto_20220304_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersectionmodel',
            name='section_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='footer_section_section_image', to='home_two.PhotoModel'),
        ),
    ]
