# Generated by Django 2.2.27 on 2022-02-10 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0002_banneradmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banneradmodel',
            name='photos',
        ),
        migrations.AddField(
            model_name='banneradmodel',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home_two.PhotoModel'),
        ),
    ]
