# Generated by Django 2.2.27 on 2022-02-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0004_aboutsectionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsectionmodel',
            name='subheading',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
