# Generated by Django 2.2.27 on 2022-02-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0005_aboutsectionmodel_subheading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsectionmodel',
            name='description',
            field=models.TextField(blank=True, max_length=465, null=True),
        ),
    ]
