# Generated by Django 2.2.27 on 2022-02-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0007_featuresectionmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuresectionmodel',
            name='heading',
        ),
    ]
