# Generated by Django 2.2.27 on 2022-02-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0008_remove_featuresectionmodel_heading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuresectionmodel',
            old_name='description',
            new_name='summary',
        ),
    ]
