# Generated by Django 2.2.27 on 2022-02-11 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0009_auto_20220211_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuresectionmodel',
            name='photo',
        ),
        migrations.AddField(
            model_name='featuresectionmodel',
            name='background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='background_image', to='home_two.PhotoModel'),
        ),
        migrations.AddField(
            model_name='featuresectionmodel',
            name='section_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='section_image', to='home_two.PhotoModel'),
        ),
    ]
