# Generated by Django 2.2.27 on 2022-02-12 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0011_auto_20220212_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitNowCtaSectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visit_now_cta_section_background_image', to='home_two.PhotoModel')),
                ('section_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visit_now_cta_section_section_image', to='home_two.PhotoModel')),
            ],
            options={
                'verbose_name': 'Visit now cta section',
                'verbose_name_plural': 'Visit now cta sections',
            },
        ),
    ]
