# Generated by Django 2.2.27 on 2022-02-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0015_homeseodetailsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeseodetailsmodel',
            name='description',
            field=models.TextField(blank=True, max_length=466, null=True),
        ),
    ]
