# Generated by Django 2.2.27 on 2022-02-13 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0016_auto_20220212_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeseodetailsmodel',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home_two.PhotoModel'),
        ),
    ]
