# Generated by Django 2.2.27 on 2022-02-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0017_auto_20220213_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomodel',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photomodel',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
