# Generated by Django 2.2.27 on 2022-02-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0018_auto_20220213_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeseodetailsmodel',
            name='url',
        ),
    ]
