# Generated by Django 2.2.27 on 2022-02-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0025_auto_20220227_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsectionmodel',
            options={'verbose_name': 'About section', 'verbose_name_plural': 'About section'},
        ),
        migrations.AlterModelOptions(
            name='featuresectionmodel',
            options={'verbose_name': 'Feature section', 'verbose_name_plural': 'Feature section'},
        ),
        migrations.AlterModelOptions(
            name='gallerysectionmodel',
            options={'verbose_name': 'Gallery section', 'verbose_name_plural': 'Gallery section'},
        ),
        migrations.AlterModelOptions(
            name='visitnowctasectionmodel',
            options={'verbose_name': 'Visit now cta section', 'verbose_name_plural': 'Visit now cta section'},
        ),
        migrations.AlterModelOptions(
            name='whychooseussectionmodel',
            options={'verbose_name': 'Why choose us section', 'verbose_name_plural': 'Why choose us section'},
        ),
    ]
