# Generated by Django 2.2.27 on 2022-03-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0028_auto_20220301_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgemodel',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
