# Generated by Django 2.2.27 on 2022-03-09 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0032_auto_20220309_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banneradmodel',
            name='photo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home_two.PhotoModel'),
        ),
    ]
