# Generated by Django 2.2.27 on 2022-03-09 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_two', '0037_auto_20220309_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitnowctasectionmodel',
            name='background_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visit_now_cta_section_background_image', to='home_two.PhotoModel'),
        ),
        migrations.AlterField(
            model_name='visitnowctasectionmodel',
            name='section_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visit_now_cta_section_section_image', to='home_two.PhotoModel'),
        ),
    ]
